version: '3.1'

services:
  nodejs:
    tty: true
    env_file:
      - ./.env.dev.docker
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - /usr/app/node_modules/
      - .:/usr/src/service/
    working_dir: /usr/src/service/
    environment:
      - TERM=xterm-256color`
      - NODE_ENV=development
      - SIG_USER=${SIG_USER}
    image: img-api-sigpharma-dev
    container_name: api-sigpharma-dev
    restart: unless-stopped
    networks:
      - app-network
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - web-root-dev:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network

volumes:
  web-root-dev:
    driver: local
    driver_opts:
      type: none
      device: /home/${SIG_USER}/2020-Dev/APIs/api.sigpharma.abc/APISig/public/
      o: bind

networks:
  app-network:
    driver: bridge
